parameters:
    twig.extension.readable_enum_value.class: Letsweb\Bundle\EnumIntDoctrineBundle\Twig\Extension\ReadableEnumIntValueExtension
    twig.extension.enum_constant.class: Letsweb\Bundle\EnumIntDoctrineBundle\Twig\Extension\EnumIntConstantExtension
    enum_type_guesser.class: Letsweb\Bundle\EnumIntDoctrineBundle\Form\EnumIntTypeGuesser

services:
    twig.extension.readable_enum_value:
        class: %twig.extension.readable_enum_value.class%
        arguments:
            - %doctrine.dbal.connection_factory.types%
        tags:
            - { name: twig.extension }

    twig.extension.enum_constant:
        class: %twig.extension.enum_constant.class%
        arguments:
            - %doctrine.dbal.connection_factory.types%
        tags:
            - { name: twig.extension }

    enum_type_guesser:
        class: %enum_type_guesser.class%
        arguments:
            - @doctrine
            - %doctrine.dbal.connection_factory.types%
        tags:
            - { name: form.type_guesser, priority: -30 }
